package projectjavadimas;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import projectjavadimas.dao.dao;
import projectjavadimas.model.modelProject;
import projectjavadimas.validasi.Validasi;

public class Daftar extends javax.swing.JFrame {

    modelProject mod = new modelProject();
    dao crud = new dao();
    Validasi val = new Validasi();
    String tamp = null;
    int lenghtTamp = 0;

    public Daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        masuk = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namdep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nambel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tgl = new javax.swing.JComboBox<>();
        bln = new javax.swing.JComboBox<>();
        thn = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        cewe = new javax.swing.JRadioButton();
        daftar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 77, 67));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pegadaian Digital");

        jLabel4.setFont(new java.awt.Font("Google Sans", 3, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mengatasi Masalah Tanpa Masalah");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(13, 13, 13))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjavadimas/img/logo3.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Google Sans", 1, 24)); // NOI18N
        jLabel7.setText("Selamat Datang di Pegadaian Emas Digital !");

        jLabel8.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        jLabel8.setText("Solusi investasi, pendanaan, dan pembayaran tagihan ");

        jLabel9.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        jLabel9.setText("dengan mudah tanpa harus keluar rumah");

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel11.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel11.setText("Sudah punya akun?");

        masuk.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        masuk.setForeground(new java.awt.Color(0, 171, 78));
        masuk.setText("Masuk");
        masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masukMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Google Sans", 1, 24)); // NOI18N
        jLabel10.setText("Selamat Datang!");

        namdep.setMargin(new java.awt.Insets(2, 8, 2, 8));
        namdep.setSelectionColor(new java.awt.Color(0, 77, 67));
        namdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namdepActionPerformed(evt);
            }
        });
        namdep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namdepKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel1.setText("Nama Depan");

        jLabel2.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel2.setText("Nama Belakang");

        nambel.setMargin(new java.awt.Insets(2, 8, 2, 8));
        nambel.setSelectionColor(new java.awt.Color(0, 77, 67));
        nambel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nambelActionPerformed(evt);
            }
        });
        nambel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nambelKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel12.setText("No. Handphone");

        hp.setMargin(new java.awt.Insets(2, 8, 2, 8));
        hp.setSelectionColor(new java.awt.Color(0, 77, 67));
        hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpActionPerformed(evt);
            }
        });
        hp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hpKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel13.setText("Username");

        user.setMargin(new java.awt.Insets(2, 8, 2, 8));
        user.setSelectionColor(new java.awt.Color(0, 77, 67));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel14.setText("Tanggal Lahir");

        tgl.setEditable(true);
        tgl.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        tgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tgl.setBorder(null);
        tgl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglActionPerformed(evt);
            }
        });

        bln.setEditable(true);
        bln.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        bln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "Septermber", "Oktober", "November", "Desember" }));
        bln.setBorder(null);
        bln.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        thn.setEditable(true);
        thn.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        thn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        thn.setBorder(null);
        thn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel15.setText("Jenis Kelamin");

        buttonGroup1.add(laki);
        laki.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        laki.setText("Laki - Laki");
        laki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(cewe);
        cewe.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        cewe.setText("Perempuan");
        cewe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cewe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceweActionPerformed(evt);
            }
        });

        daftar.setBackground(new java.awt.Color(0, 77, 67));
        daftar.setFont(new java.awt.Font("Google Sans", 1, 20)); // NOI18N
        daftar.setForeground(new java.awt.Color(255, 255, 255));
        daftar.setText("Daftar");
        daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daftarMouseEntered(evt);
            }
        });
        daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel16.setText("Daftar akun untuk memulai investasi, gadai dan kemudahan transaksi lainnya");

        jLabel17.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel17.setText("Password");

        pw.setMargin(new java.awt.Insets(2, 8, 2, 8));
        pw.setSelectionColor(new java.awt.Color(0, 77, 67));
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15))
                                    .addGap(32, 32, 32)
                                    .addComponent(laki)
                                    .addGap(50, 50, 50)
                                    .addComponent(cewe))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(57, 57, 57)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2))
                                                .addGap(21, 21, 21))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(54, 54, 54)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nambel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namdep, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masuk)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namdep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nambel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pw, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(laki)
                    .addComponent(cewe))
                .addGap(29, 29, 29)
                .addComponent(daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(masuk))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(80, 80, 80)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpActionPerformed

    private void nambelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nambelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nambelActionPerformed

    private void namdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namdepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namdepActionPerformed

    private void masukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masukMouseExited
        masuk.setForeground(new Color(0, 171, 78));
    }//GEN-LAST:event_masukMouseExited

    private void masukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masukMouseEntered
        masuk.setForeground(new Color(0, 77, 67));
        masuk.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_masukMouseEntered

    private void masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masukMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_masukMouseClicked

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void ceweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceweActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceweActionPerformed

    private void daftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMouseEntered
        masuk.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_daftarMouseEntered

    private void daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarActionPerformed
        String tanggal, bul, tahun, jk;
        String bulan = null;
        tanggal = (String) tgl.getSelectedItem();
        bul = (String) bln.getSelectedItem();
        if (bul.equalsIgnoreCase("Januari")) {
            bulan = "1";
        } else if (bul.equalsIgnoreCase("Februari")) {
            bulan = "2";
        } else if (bul.equalsIgnoreCase("Maret")) {
            bulan = "3";
        } else if (bul.equalsIgnoreCase("April")) {
            bulan = "4";
        } else if (bul.equalsIgnoreCase("Mei")) {
            bulan = "5";
        } else if (bul.equalsIgnoreCase("Juni")) {
            bulan = "6";
        } else if (bul.equalsIgnoreCase("Juli")) {
            bulan = "7";
        } else if (bul.equalsIgnoreCase("Agustus")) {
            bulan = "8";
        } else if (bul.equalsIgnoreCase("September")) {
            bulan = "9";
        } else if (bul.equalsIgnoreCase("Oktober")) {
            bulan = "10";
        } else if (bul.equalsIgnoreCase("November")) {
            bulan = "11";
        } else if (bul.equalsIgnoreCase("Desember")) {
            bulan = "12";
        }
        else {
            bulan = null;
        }
        tahun = (String) thn.getSelectedItem();
        if (laki.isSelected()) {
            jk = "l";
        } else {
            jk = "p";
        }
        String namaDepan, namaBelakang;
        namaDepan = namdep.getText();
        namaBelakang = nambel.getText();
        boolean valNamdep = val.validasiNama(namaDepan);
        boolean valNambel = val.validasiNama(namaBelakang);

        //validasi
        if (namdep.getText().isEmpty() || nambel.getText().isEmpty() || hp.getText().isEmpty() || user.getText().isEmpty() || pw.getText().isEmpty() || tanggal.isEmpty() || bulan.isEmpty() || tahun.isEmpty() || jk.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ada data yang kosong");
        } else {
            try {
                mod.setNamdep(namdep.getText());
                mod.setNambel(nambel.getText());
                mod.setNo_hp(hp.getText());
                mod.setUsername(user.getText());
                mod.setPassword(pw.getText());
                mod.setTanggal(tanggal);
                mod.setBulan(bulan);
                mod.setTahun(tahun);
                mod.setJ_kelamin(jk);
                crud.daftar(mod);
                JOptionPane.showMessageDialog(null, "Data Berhasil Diinput");
                MenuUtama main = new MenuUtama(user.getText());
                Profil prof = new Profil(user.getText());
                main.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Data gagal di input");
            }

        }
    }//GEN-LAST:event_daftarActionPerformed

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwActionPerformed

    private void tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglActionPerformed

    private void namdepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namdepKeyTyped
        tamp = namdep.getText();
        lenghtTamp = tamp.length();
        val.valNama(evt, lenghtTamp, 50);
    }//GEN-LAST:event_namdepKeyTyped

    private void nambelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nambelKeyTyped
        tamp = nambel.getText();
        lenghtTamp = tamp.length();
        val.valNama(evt, lenghtTamp, 50);
    }//GEN-LAST:event_nambelKeyTyped

    private void userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyTyped
        tamp = user.getText();
        lenghtTamp = tamp.length();
        val.valUname(evt, lenghtTamp, 50);
                
    }//GEN-LAST:event_userKeyTyped

    private void pwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyTyped
        tamp = pw.getText();
        lenghtTamp = tamp.length();
        val.valUname(evt, lenghtTamp, 50);
    }//GEN-LAST:event_pwKeyTyped

    private void hpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hpKeyTyped
        tamp = hp.getText();
        lenghtTamp = tamp.length();
        val.valAngka(evt, lenghtTamp, 13);
    }//GEN-LAST:event_hpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bln;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cewe;
    private javax.swing.JButton daftar;
    private javax.swing.JTextField hp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel masuk;
    private javax.swing.JTextField nambel;
    private javax.swing.JTextField namdep;
    private javax.swing.JPasswordField pw;
    private javax.swing.JComboBox<String> tgl;
    private javax.swing.JComboBox<String> thn;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
