package projectjavadimas;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projectjavadimas.model.modelProject;
import projectjavadimas.dao.dao;

public class Gadai extends javax.swing.JFrame {

    modelProject mod = new modelProject();
    dao crud = new dao();
    Login log = new Login();
    String user;
    int berat_emas, harga_emas,jml, total;
    String tanggal, bul, tahun, kantorPelayanan, waktu;
    String jns, surat_emas, brt, jum, bulan = null;
    
    public Gadai() {
        initComponents();
    }
    
    public Gadai(String u) {
        initComponents();
        this.user = u;
        System.out.println("gadai" + user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        beranda = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();
        gadai = new javax.swing.JLabel();
        riwayat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        langkah1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        berat = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lengkap = new javax.swing.JRadioButton();
        tdk_lengkap = new javax.swing.JRadioButton();
        batal = new javax.swing.JButton();
        jumlah_keping = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        langkah2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        kantor = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        tgl = new javax.swing.JComboBox<>();
        bln = new javax.swing.JComboBox<>();
        thn = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jam = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        lanjut = new javax.swing.JButton();
        langkah3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        konfir = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        TotalAkhir = new javax.swing.JLabel();
        jenis_fiks = new javax.swing.JLabel();
        jumlah_fiks = new javax.swing.JLabel();
        berat_fiks = new javax.swing.JLabel();
        surat_fiks = new javax.swing.JLabel();
        kantor_fiks = new javax.swing.JLabel();
        jadwal_fiks = new javax.swing.JLabel();
        waktu_fiks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 77, 67));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pegadaian Digital");

        jLabel4.setFont(new java.awt.Font("Google Sans", 3, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mengatasi Masalah Tanpa Masalah");

        beranda.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 255));
        beranda.setText("Beranda");
        beranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beranda.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                berandaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        profil.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        profil.setForeground(new java.awt.Color(255, 255, 255));
        profil.setText("Profil");
        profil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilMouseClicked(evt);
            }
        });

        gadai.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        gadai.setForeground(new java.awt.Color(255, 255, 255));
        gadai.setText("Gadai Emas");
        gadai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gadai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gadaiMouseClicked(evt);
            }
        });

        riwayat.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        riwayat.setForeground(new java.awt.Color(255, 255, 255));
        riwayat.setText("Riwayat");
        riwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(beranda)
                .addGap(48, 48, 48)
                .addComponent(gadai)
                .addGap(45, 45, 45)
                .addComponent(riwayat)
                .addGap(42, 42, 42)
                .addComponent(profil)
                .addGap(42, 42, 42)
                .addComponent(logout)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(beranda)
                        .addComponent(logout)
                        .addComponent(profil)
                        .addComponent(gadai)
                        .addComponent(riwayat)))
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjavadimas/img/logo1-removebg-preview.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel8.setText("1. Input jenis dan jumlah keping emas");

        jLabel9.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel9.setText("2. Tentukan waktu kedatangan");

        jLabel10.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel10.setText("3. Tentukan titik penebusan");

        jLabel11.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel11.setText("4. Hasil transaksi akan muncul");

        jLabel12.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel12.setText("5. Cek riwayat transaksi");

        jLabel13.setFont(new java.awt.Font("Google Sans", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 171, 78));
        jLabel13.setText("GADAI EMAS");

        jLabel14.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(191, 215, 48));
        jLabel14.setText("cara cepat gadai emas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel13))
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addGap(49, 49, 49)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.setBackground(new java.awt.Color(245, 245, 245));
        jTabbedPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane3.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N

        langkah1.setBackground(new java.awt.Color(245, 245, 245));
        langkah1.setFocusTraversalPolicyProvider(true);
        langkah1.setPreferredSize(new java.awt.Dimension(445, 512));

        jPanel4.setBackground(new java.awt.Color(0, 171, 78));

        jLabel15.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Kredit Cepat Aman (KCA) adalah kredit dengan sistem gadai yang diberikan kepada semua golongan nasabah,");

        jLabel16.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("baik untuk kebutuhan konsumtif maupun kebutuhan produktif. KCA merupakan solusi terpercaya untuk");

        jLabel17.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("mendapatkan pinjaman secara mudah, cepat dan aman.");

        jLabel18.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Lakukan pengajuan kredit sekarang dengan memilih salah satu agunan yang ingin anda gadaikan.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addGap(0, 0, 0)
                .addComponent(jLabel16)
                .addGap(0, 0, 0)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jenis.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emas Antam", "Emas Antam Retro", "Emas Antam Batik", "Emas Lantakan" }));
        jenis.setBorder(null);
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel19.setText("Jenis Emas");

        jLabel20.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel20.setText("Jumlah Keping");

        jLabel21.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel21.setText("Berat Keping");

        berat.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        berat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "9", "10" }));
        berat.setBorder(null);
        berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel22.setText("gram");

        jLabel23.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel23.setText("Kelengkapan Surat");

        buttonGroup1.add(lengkap);
        lengkap.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        lengkap.setText("Lengkap");
        lengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengkapActionPerformed(evt);
            }
        });

        buttonGroup1.add(tdk_lengkap);
        tdk_lengkap.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        tdk_lengkap.setText("Tidak Lengkap");
        tdk_lengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdk_lengkapActionPerformed(evt);
            }
        });

        batal.setBackground(new java.awt.Color(0, 171, 78));
        batal.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        batal.setForeground(new java.awt.Color(255, 255, 255));
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        jumlah_keping.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jumlah_keping.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "9", "10" }));
        jumlah_keping.setBorder(null);
        jumlah_keping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_kepingActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel43.setText("keping");

        javax.swing.GroupLayout langkah1Layout = new javax.swing.GroupLayout(langkah1);
        langkah1.setLayout(langkah1Layout);
        langkah1Layout.setHorizontalGroup(
            langkah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(langkah1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(langkah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addGap(41, 41, 41)
                .addGroup(langkah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(langkah1Layout.createSequentialGroup()
                        .addComponent(berat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel22))
                    .addGroup(langkah1Layout.createSequentialGroup()
                        .addComponent(lengkap)
                        .addGap(32, 32, 32)
                        .addComponent(tdk_lengkap))
                    .addGroup(langkah1Layout.createSequentialGroup()
                        .addComponent(jumlah_keping, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel43)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(langkah1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, langkah1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        langkah1Layout.setVerticalGroup(
            langkah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, langkah1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(langkah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(langkah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jumlah_keping, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(langkah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(berat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(langkah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengkap)
                    .addComponent(tdk_lengkap)
                    .addComponent(jLabel23))
                .addGap(33, 33, 33)
                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane3.addTab("Langkah 1", langkah1);

        langkah2.setBackground(new java.awt.Color(245, 245, 245));

        jLabel24.setFont(new java.awt.Font("Google Sans", 1, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 77, 67));
        jLabel24.setText("Waktu");

        jLabel25.setFont(new java.awt.Font("Google Sans", 1, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 171, 78));
        jLabel25.setText("Operasional");

        jLabel27.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        jLabel27.setText("08.00 - 16.00 WIB");

        jLabel28.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel28.setText("Pilih Kantor Pelayanan");

        kantor.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        kantor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pegadaian Kantor Wilayah X", "Pegadaian Gegerkalong", "Pegadaian UPC Buah Batu", "Pegadaian Kiara Condong", "Pegadaian Sukajadi", "Pegadaian UPC Cicendo" }));

        jLabel29.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel29.setText("Jadwal Kedatangan");

        tgl.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        tgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tgl.setBorder(null);
        tgl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglActionPerformed(evt);
            }
        });

        bln.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        bln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "Septermber", "Oktober", "November", "Desember" }));
        bln.setBorder(null);
        bln.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        thn.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        thn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023" }));
        thn.setBorder(null);
        thn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thnActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel30.setText("Waktu Kedatangan");

        jam.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.00", "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00" }));
        jam.setBorder(null);
        jam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel31.setText("WIB");

        lanjut.setBackground(new java.awt.Color(0, 171, 78));
        lanjut.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        lanjut.setForeground(new java.awt.Color(255, 255, 255));
        lanjut.setText("Simpan");
        lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout langkah2Layout = new javax.swing.GroupLayout(langkah2);
        langkah2.setLayout(langkah2Layout);
        langkah2Layout.setHorizontalGroup(
            langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(langkah2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(langkah2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(langkah2Layout.createSequentialGroup()
                        .addGroup(langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(65, 65, 65)
                        .addGroup(langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(langkah2Layout.createSequentialGroup()
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kantor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(langkah2Layout.createSequentialGroup()
                                .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)))))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, langkah2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        langkah2Layout.setVerticalGroup(
            langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(langkah2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(57, 57, 57)
                .addGroup(langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(kantor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(langkah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(lanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane3.addTab("Langkah 2", langkah2);

        langkah3.setBackground(new java.awt.Color(245, 245, 245));
        langkah3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                langkah3MouseEntered(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Google Sans", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 77, 67));
        jLabel26.setText("Perkiraan");

        jLabel32.setFont(new java.awt.Font("Google Sans", 1, 22)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 171, 78));
        jLabel32.setText("Pinjaman");

        jLabel34.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel34.setText("Jenis Emas");

        jLabel35.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel35.setText("Jumlah Keping");

        jLabel36.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel36.setText("Berat Keping");

        jLabel37.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel37.setText("Kelengkapan Surat");

        jLabel38.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel38.setText("Kantor Pelayanan");

        jLabel39.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel39.setText("Jadwal Kedatangan");

        jLabel40.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel40.setText("Waktu Kedatangan");

        konfir.setBackground(new java.awt.Color(0, 171, 78));
        konfir.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        konfir.setForeground(new java.awt.Color(255, 255, 255));
        konfir.setText("Konfirmasi");
        konfir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 171, 78));
        reset.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Batal");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        TotalAkhir.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        TotalAkhir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalAkhir.setText("Rp.  0");
        TotalAkhir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jenis_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jenis_fiks.setText("-");

        jumlah_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jumlah_fiks.setText("-");

        berat_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        berat_fiks.setText("-");

        surat_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        surat_fiks.setText("-");

        kantor_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        kantor_fiks.setText("-");

        jadwal_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jadwal_fiks.setText("-");

        waktu_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        waktu_fiks.setText("-");

        javax.swing.GroupLayout langkah3Layout = new javax.swing.GroupLayout(langkah3);
        langkah3.setLayout(langkah3Layout);
        langkah3Layout.setHorizontalGroup(
            langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(langkah3Layout.createSequentialGroup()
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(langkah3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(langkah3Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(95, 95, 95)
                                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenis_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(berat_fiks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                                        .addComponent(jumlah_fiks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, langkah3Layout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kantor_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, langkah3Layout.createSequentialGroup()
                                    .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel36)
                                        .addComponent(jLabel35)
                                        .addComponent(jLabel37)
                                        .addComponent(jLabel40))
                                    .addGap(48, 48, 48)
                                    .addComponent(surat_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(langkah3Layout.createSequentialGroup()
                                    .addComponent(jLabel39)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jadwal_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(waktu_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(langkah3Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TotalAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(langkah3Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)))))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, langkah3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(konfir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        langkah3Layout.setVerticalGroup(
            langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(langkah3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel32))
                .addGap(0, 0, 0)
                .addComponent(TotalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jenis_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jumlah_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(berat_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(surat_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(kantor_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jadwal_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(waktu_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(langkah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(konfir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Langkah 3", langkah3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(new Color(186, 211, 51));
        logout.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(new Color(255, 255, 255));
        logout.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_logoutMouseExited

    private void lengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengkapActionPerformed

    private void tdk_lengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdk_lengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdk_lengkapActionPerformed

    private void tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglActionPerformed

    private void thnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thnActionPerformed

    private void jamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        TotalAkhir.setText("Rp. -");
        jenis_fiks.setText("-");
        jumlah_fiks.setText("-");
        berat_fiks.setText("-");
        surat_fiks.setText("-");
        kantor_fiks.setText("-");
        jadwal_fiks.setText("-");
        waktu_fiks.setText("-");
    }//GEN-LAST:event_resetActionPerformed

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        MenuUtama main = new MenuUtama(user);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_berandaMouseClicked

    private void profilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseClicked
        
        try {
            Profil prof = new Profil(user);
            prof.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Gadai.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_profilMouseClicked

    private void riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseClicked
        try {
            Riwayat riw = new Riwayat(user);
            riw.setVisible(true);
        } catch (SQLException ex) {
            System.out.println("Terjadi kesalahan pada : " + ex);
        }
        this.dispose();
    }//GEN-LAST:event_riwayatMouseClicked

    private void gadaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gadaiMouseClicked
        Gadai gad = new Gadai();
        gad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gadaiMouseClicked

    private void berandaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_berandaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_berandaAncestorAdded

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        MenuUtama main = new MenuUtama();
        main.setVisible(true);
    }//GEN-LAST:event_batalActionPerformed

    private void lanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutActionPerformed
        JOptionPane.showMessageDialog(null,"Cek Kelengkapan data di slide ke 3");
        jns = (String) jenis.getSelectedItem();
        if(jns.equalsIgnoreCase("Emas Antam")){
            harga_emas = 1019000;
        }
        else if(jns.equalsIgnoreCase("Emas Antam Retro")){
            harga_emas = 977000;
        }
        else if(jns.equalsIgnoreCase("Emas Antam Batik")){
            harga_emas = 1174000;
        }
        else if(jns.equalsIgnoreCase("Emas Lantakan")){
            harga_emas = 974000;
        }
        else {
            harga_emas = 0;
        }
        brt = (String) berat.getSelectedItem();
        this.berat_emas = Integer.parseInt(brt);
        jum = (String) jumlah_keping.getSelectedItem();
        this.jml = Integer.parseInt(jum);
        if(lengkap.isSelected()){
            surat_emas = "Lengkap";
        }
        else {
            surat_emas = "Tidak Lengkap";
        }
        this.total = this.harga_emas * this.berat_emas * this.jml;
        String text = Integer.toString(this.total);
        kantorPelayanan = (String) kantor.getSelectedItem();
        tanggal = (String) tgl.getSelectedItem();
        bul = (String) bln.getSelectedItem();
        
        if(bul.equalsIgnoreCase("Januari")){
            bulan = "1";
        }
        else if(bul.equalsIgnoreCase("Februari")){
            bulan = "2";
        }
        else if(bul.equalsIgnoreCase("Maret")){
            bulan = "3";
        }
        else if(bul.equalsIgnoreCase("April")){
            bulan = "4";
        }
        else if(bul.equalsIgnoreCase("Mei")){
            bulan = "5";
        }
        else if(bul.equalsIgnoreCase("Juni")){
            bulan = "6";
        }
        else if(bul.equalsIgnoreCase("Juli")){
            bulan = "7";
        }
        else if(bul.equalsIgnoreCase("Agustus")){
            bulan = "8";
        }
        else if(bul.equalsIgnoreCase("September")){
            bulan = "9";
        }
        else if(bul.equalsIgnoreCase("Oktober")){
            bulan = "10";
        }
        else if(bul.equalsIgnoreCase("November")){
            bulan = "11";
        }
        else if(bul.equalsIgnoreCase("Desember")){
            bulan = "12";
        }
        else {
            bulan = null;
        }
        tahun = (String) thn.getSelectedItem();
        waktu = (String) jam.getSelectedItem();
        mod.setUsername(this.user);
        mod.setJenis(jns);
        mod.setJumlah(jml);
        mod.setBerat(berat_emas);
        mod.setSurat(surat_emas);
        mod.setKantor(kantorPelayanan);
        mod.setJadwal_tgl(tanggal);
        mod.setJadwal_bln(bulan);
        mod.setJadwal_thn(tahun);
        mod.setWaktu(waktu);
        TotalAkhir.setText("Rp. " + text);
        jenis_fiks.setText(jns);
        jumlah_fiks.setText(jum + " keping");
        berat_fiks.setText(brt + " gram");
        surat_fiks.setText(surat_emas);
        kantor_fiks.setText(kantorPelayanan);
        jadwal_fiks.setText(tanggal + " " + bul + " " + tahun);
        waktu_fiks.setText(waktu + " WIB");
    }//GEN-LAST:event_lanjutActionPerformed

    private void konfirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirActionPerformed
        
        try {
            crud.langkah(mod, total);
            Riwayat riw = new Riwayat(mod.getUsername());
            riw.setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(null,"Terimakasih sudah melakukan transaksi :)");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Data gagal di input");
        }
    }//GEN-LAST:event_konfirActionPerformed

    private void beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void jumlah_kepingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_kepingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_kepingActionPerformed

    private void langkah3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langkah3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_langkah3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gadai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gadai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gadai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gadai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gadai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalAkhir;
    private javax.swing.JButton batal;
    private javax.swing.JLabel beranda;
    private javax.swing.JComboBox<String> berat;
    private javax.swing.JLabel berat_fiks;
    private javax.swing.JComboBox<String> bln;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel gadai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel jadwal_fiks;
    private javax.swing.JComboBox<String> jam;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel jenis_fiks;
    private javax.swing.JLabel jumlah_fiks;
    private javax.swing.JComboBox<String> jumlah_keping;
    private javax.swing.JComboBox<String> kantor;
    private javax.swing.JLabel kantor_fiks;
    private javax.swing.JButton konfir;
    private javax.swing.JPanel langkah1;
    private javax.swing.JPanel langkah2;
    private javax.swing.JPanel langkah3;
    private javax.swing.JButton lanjut;
    private javax.swing.JRadioButton lengkap;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel profil;
    private javax.swing.JButton reset;
    private javax.swing.JLabel riwayat;
    private javax.swing.JLabel surat_fiks;
    private javax.swing.JRadioButton tdk_lengkap;
    private javax.swing.JComboBox<String> tgl;
    private javax.swing.JComboBox<String> thn;
    private javax.swing.JLabel waktu_fiks;
    // End of variables declaration//GEN-END:variables
}
