package projectjavadimas;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import projectjavadimas.dao.dao;
import projectjavadimas.model.modelProject;
import projectjavadimas.validasi.Validasi;

public class Profil extends javax.swing.JFrame {

    modelProject mod = new modelProject();
    dao crud = new dao();
    String user;
    Validasi val = new Validasi();
    String tamp = null;
    int lenghtTamp = 0;
   
    public Profil() {
        initComponents();
    }
    
    public Profil(String u) throws SQLException {
        initComponents();
        user = u;
        System.out.println("Profil : " + user);
        label_nama.setText(user);
        tampilTableAnggota(user);
    }
    
    public void tampilTableAnggota(String u) throws SQLException {
        tabelAnggota.setModel(crud.tabelAnggota(u));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        beranda = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();
        gadai = new javax.swing.JLabel();
        riwayat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tgl = new javax.swing.JComboBox<>();
        bln = new javax.swing.JComboBox<>();
        thn = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        cewe = new javax.swing.JRadioButton();
        update = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        nambel = new javax.swing.JTextField();
        namdep = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 77, 67));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pegadaian Digital");

        jLabel4.setFont(new java.awt.Font("Google Sans", 3, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mengatasi Masalah Tanpa Masalah");

        beranda.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 255));
        beranda.setText("Beranda");
        beranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                berandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                berandaMouseExited(evt);
            }
        });

        logout.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        profil.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        profil.setForeground(new java.awt.Color(255, 255, 255));
        profil.setText("Profil");
        profil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilMouseExited(evt);
            }
        });

        gadai.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        gadai.setForeground(new java.awt.Color(255, 255, 255));
        gadai.setText("Gadai Emas");
        gadai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gadai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gadaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gadaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gadaiMouseExited(evt);
            }
        });

        riwayat.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        riwayat.setForeground(new java.awt.Color(255, 255, 255));
        riwayat.setText("Riwayat");
        riwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beranda)
                .addGap(48, 48, 48)
                .addComponent(gadai)
                .addGap(45, 45, 45)
                .addComponent(riwayat)
                .addGap(42, 42, 42)
                .addComponent(profil)
                .addGap(42, 42, 42)
                .addComponent(logout)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(beranda)
                        .addComponent(logout)
                        .addComponent(profil)
                        .addComponent(gadai)
                        .addComponent(riwayat)))
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(13, 13, 13))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        label_nama.setEditable(false);
        label_nama.setBackground(new java.awt.Color(245, 245, 245));
        label_nama.setFont(new java.awt.Font("Google Sans", 1, 36)); // NOI18N
        label_nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_nama.setText("username");
        label_nama.setBorder(null);
        label_nama.setMargin(new java.awt.Insets(3, 6, 3, 6));
        label_nama.setMaximumSize(new java.awt.Dimension(80, 24));
        label_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_namaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel2.setText("Selamat akun anda sudah terdaftar di");

        jLabel5.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        jLabel5.setText("Klik tabel diatas untuk melihat data !!!");

        tabelAnggota.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelAnggota.setGridColor(new java.awt.Color(0, 0, 0));
        tabelAnggota.setSelectionBackground(new java.awt.Color(0, 77, 67));
        tabelAnggota.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAnggota);

        jLabel12.setFont(new java.awt.Font("Google Sans", 1, 12)); // NOI18N
        jLabel12.setText("Aplikasi Pegadaian Emas Digital");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjavadimas/img/logo1-removebg-preview.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel13.setText("Username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(81, 81, 81))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(21, 21, 21))
        );

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));

        jLabel6.setFont(new java.awt.Font("Google Sans", 1, 24)); // NOI18N
        jLabel6.setText("Data Nasabah");

        jLabel7.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel7.setText("Nama Depan");

        jLabel8.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel8.setText("Nama Belakang");

        jLabel9.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel9.setText("No. Handphone");

        jLabel10.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel10.setText("Username");

        jLabel11.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel11.setText("Password");

        jLabel14.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel14.setText("Tanggal Lahir");

        tgl.setEditable(true);
        tgl.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        tgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tgl.setBorder(null);
        tgl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglActionPerformed(evt);
            }
        });

        bln.setEditable(true);
        bln.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        bln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "Septermber", "Oktober", "November", "Desember" }));
        bln.setBorder(null);
        bln.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        thn.setEditable(true);
        thn.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        thn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        thn.setBorder(null);
        thn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel15.setText("Jeni Kelamin");

        buttonGroup1.add(laki);
        laki.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        laki.setText("Laki - Laki");
        laki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(cewe);
        cewe.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        cewe.setText("Perempuan");
        cewe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cewe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceweActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 77, 67));
        update.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Simpan Perubahan");
        update.setBorder(null);
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        password.setEditable(false);
        password.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        password.setMargin(new java.awt.Insets(2, 9, 2, 9));
        password.setSelectionColor(new java.awt.Color(0, 77, 67));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        username.setEditable(false);
        username.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        username.setMargin(new java.awt.Insets(2, 8, 2, 8));
        username.setSelectionColor(new java.awt.Color(0, 77, 67));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        nohp.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        nohp.setMargin(new java.awt.Insets(2, 8, 2, 8));
        nohp.setSelectionColor(new java.awt.Color(0, 77, 67));
        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });
        nohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nohpKeyTyped(evt);
            }
        });

        nambel.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        nambel.setMargin(new java.awt.Insets(2, 8, 2, 8));
        nambel.setSelectionColor(new java.awt.Color(0, 77, 67));
        nambel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nambelKeyTyped(evt);
            }
        });

        namdep.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        namdep.setMargin(new java.awt.Insets(2, 8, 2, 8));
        namdep.setSelectionColor(new java.awt.Color(0, 77, 67));
        namdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namdepActionPerformed(evt);
            }
        });
        namdep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namdepKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("tidak bisa diubah");

        jLabel17.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("tidak bisa diubah");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(55, 55, 55))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(55, 55, 55))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel14))
                                    .addGap(69, 69, 69)))
                            .addComponent(jLabel15)
                            .addComponent(jLabel7))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(laki)
                                .addGap(18, 18, 18)
                                .addComponent(cewe))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nambel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namdep, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))))
                    .addComponent(jLabel6))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(namdep, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nambel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laki)
                    .addComponent(cewe)
                    .addComponent(jLabel15))
                .addGap(45, 45, 45)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void berandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseEntered
        beranda.setForeground(new Color(186, 211, 51));
        beranda.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_berandaMouseEntered

    private void berandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseExited
        beranda.setForeground(new Color(255, 255, 255));
        beranda.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_berandaMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(new Color(186, 211, 51));
        logout.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(new Color(255, 255, 255));
        logout.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_logoutMouseExited

    private void profilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profilMouseClicked

    private void profilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseEntered
        profil.setForeground(new Color(186, 211, 51));
        profil.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_profilMouseEntered

    private void profilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseExited
        profil.setForeground(new Color(255, 255, 255));
        profil.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_profilMouseExited

    private void gadaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gadaiMouseEntered
        gadai.setForeground(new Color(186, 211, 51));
        gadai.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_gadaiMouseEntered

    private void gadaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gadaiMouseExited
        gadai.setForeground(new Color(255, 255, 255));
        gadai.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_gadaiMouseExited

    private void riwayatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseEntered
        riwayat.setForeground(new Color(186, 211, 51));
        riwayat.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_riwayatMouseEntered

    private void riwayatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseExited
        riwayat.setForeground(new Color(255, 255, 255));
        riwayat.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_riwayatMouseExited

    private void tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void ceweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceweActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceweActionPerformed

    private void riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseClicked
        try {
            Riwayat riw = new Riwayat(user);
            riw.setVisible(true);
        } catch (SQLException ex) {
            System.out.println("Terjadi kesalahan pada : " + ex);
        }
        this.dispose();
    }//GEN-LAST:event_riwayatMouseClicked

    private void gadaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gadaiMouseClicked
        Gadai gad = new Gadai(user);
        gad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gadaiMouseClicked

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        MenuUtama main = new MenuUtama(user);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_berandaMouseClicked

    private void label_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_namaActionPerformed

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        int baris = tabelAnggota.getSelectedRow();
        String pecah = tabelAnggota.getModel().getValueAt(baris, 5).toString();
        String[] lahir = pecah.split("-");
        String tanggal_lahir = lahir[2];
        String bln_lhr = lahir[1];
        String tahun_lahir = lahir[0];
        String bulan_lahir = null;
        if(bln_lhr.equalsIgnoreCase("01")){
            bulan_lahir = "Januari";
        }
        else if(bln_lhr.equalsIgnoreCase("02")){
            bulan_lahir = "Februari";
        }
        else if(bln_lhr.equalsIgnoreCase("03")){
            bulan_lahir = "Maret";
        }
        else if(bln_lhr.equalsIgnoreCase("04")){
            bulan_lahir = "April";
        }
        else if(bln_lhr.equalsIgnoreCase("05")){
            bulan_lahir = "Mei";
        }
        else if(bln_lhr.equalsIgnoreCase("06")){
            bulan_lahir = "Juni";
        }
        else if(bln_lhr.equalsIgnoreCase("07")){
            bulan_lahir = "Juli";
        }
        else if(bln_lhr.equalsIgnoreCase("08")){
            bulan_lahir = "Agustus";
        }
        else if(bln_lhr.equalsIgnoreCase("09")){
            bulan_lahir = "September";
        }
        else if(bln_lhr.equalsIgnoreCase("10")){
            bulan_lahir = "Oktober";
        }
        else if(bln_lhr.equalsIgnoreCase("11")){
            bulan_lahir = "November";
        }
        else if(bln_lhr.equalsIgnoreCase("12")){
            bulan_lahir = "Desember";
        }
        namdep.setText(tabelAnggota.getModel().getValueAt(baris, 2).toString());
        nambel.setText(tabelAnggota.getModel().getValueAt(baris, 3).toString());
        nohp.setText(tabelAnggota.getModel().getValueAt(baris, 4).toString());
        username.setText(tabelAnggota.getModel().getValueAt(baris, 0).toString());
        password.setText(tabelAnggota.getModel().getValueAt(baris, 1).toString());
        tgl.setSelectedItem(tanggal_lahir);
        bln.setSelectedItem(bulan_lahir);
        thn.setSelectedItem(tahun_lahir);
        String gender = tabelAnggota.getModel().getValueAt(baris, 6).toString();
        if(gender.equalsIgnoreCase("l")){
            laki.doClick();
        }
        else {
            cewe.doClick();
        }
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String tanggal, bul, tahun, jk;
        String bulan = null;
        tanggal = (String) tgl.getSelectedItem();
        bul = (String) bln.getSelectedItem();
        if(bul.equalsIgnoreCase("Januari")){
            bulan = "1";
        }
        else if(bul.equalsIgnoreCase("Februari")){
            bulan = "2";
        }
        else if(bul.equalsIgnoreCase("Maret")){
            bulan = "3";
        }
        else if(bul.equalsIgnoreCase("April")){
            bulan = "4";
        }
        else if(bul.equalsIgnoreCase("Mei")){
            bulan = "5";
        }
        else if(bul.equalsIgnoreCase("Juni")){
            bulan = "6";
        }
        else if(bul.equalsIgnoreCase("Juli")){
            bulan = "7";
        }
        else if(bul.equalsIgnoreCase("Agustus")){
            bulan = "8";
        }
        else if(bul.equalsIgnoreCase("September")){
            bulan = "9";
        }
        else if(bul.equalsIgnoreCase("Oktober")){
            bulan = "10";
        }
        else if(bul.equalsIgnoreCase("November")){
            bulan = "11";
        }
        else if(bul.equalsIgnoreCase("Desember")){
            bulan = "12";
        }
        else{
            bulan = null;
        }
        tahun = (String) thn.getSelectedItem();
        if(laki.isSelected()){
            jk = "l";
        }
        else {
            jk = "p";
        }
        if(namdep.getText().isEmpty() || nambel.getText().isEmpty() || nohp.getText().isEmpty() || username.getText().isEmpty() || password.getText().isEmpty() || tanggal.isEmpty() || bulan.isEmpty() || tahun.isEmpty() || jk.isEmpty()){
            JOptionPane.showMessageDialog(null,"Ada data yang kosong");
        }
        else {
            try{
                mod.setNamdep(namdep.getText());
                mod.setNambel(nambel.getText());
                mod.setNo_hp(nohp.getText());
                mod.setUsername(username.getText());
                mod.setPassword(password.getText());
                mod.setTanggal(tanggal);
                mod.setBulan(bulan);
                mod.setTahun(tahun);
                mod.setJ_kelamin(jk);
                crud.editAnggota(mod, user);
                JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
                Profil prof = new Profil(mod.getUsername());
                prof.setVisible(true);
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Data gagal di input");
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void namdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namdepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namdepActionPerformed

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpActionPerformed

    private void namdepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namdepKeyTyped
        tamp = namdep.getText();
        lenghtTamp = tamp.length();
        val.valNama(evt, lenghtTamp, 50);
    }//GEN-LAST:event_namdepKeyTyped

    private void nambelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nambelKeyTyped
        tamp = nambel.getText();
        lenghtTamp = tamp.length();
        val.valNama(evt, lenghtTamp, 50);
    }//GEN-LAST:event_nambelKeyTyped

    private void nohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nohpKeyTyped
        tamp = nohp.getText();
        lenghtTamp = tamp.length();
        val.valAngka(evt, lenghtTamp, 13);
    }//GEN-LAST:event_nohpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Profil().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beranda;
    private javax.swing.JComboBox<String> bln;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cewe;
    private javax.swing.JLabel gadai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField label_nama;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField nambel;
    private javax.swing.JTextField namdep;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField password;
    private javax.swing.JLabel profil;
    private javax.swing.JLabel riwayat;
    private javax.swing.JTable tabelAnggota;
    private javax.swing.JComboBox<String> tgl;
    private javax.swing.JComboBox<String> thn;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
