package projectjavadimas;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projectjavadimas.dao.dao;

public class Riwayat extends javax.swing.JFrame {

    String user;
    dao crud = new dao();
    String total;
    
    public Riwayat() {
        initComponents();
    }
    
    public Riwayat(String u) throws SQLException {
        initComponents();
        user = u;
        tampilTable(user);
    }

    public void tampilTable(String u) throws SQLException {
        tabelRiwayat.setModel(crud.tampilTabel(u));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        beranda = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();
        gadai = new javax.swing.JLabel();
        riwayat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRiwayat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        waktu_fiks = new javax.swing.JLabel();
        jadwal_fiks = new javax.swing.JLabel();
        kantor_fiks = new javax.swing.JLabel();
        surat_fiks = new javax.swing.JLabel();
        berat_fiks = new javax.swing.JLabel();
        jumlah_fiks = new javax.swing.JLabel();
        jenis_fiks = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TotalAkhir = new javax.swing.JLabel();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 77, 67));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pegadaian Digital");

        jLabel4.setFont(new java.awt.Font("Google Sans", 3, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mengatasi Masalah Tanpa Masalah");

        beranda.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 255));
        beranda.setText("Beranda");
        beranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                berandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                berandaMouseExited(evt);
            }
        });

        logout.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        profil.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        profil.setForeground(new java.awt.Color(255, 255, 255));
        profil.setText("Profil");
        profil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilMouseExited(evt);
            }
        });

        gadai.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        gadai.setForeground(new java.awt.Color(255, 255, 255));
        gadai.setText("Gadai Emas");
        gadai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gadai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gadaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gadaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gadaiMouseExited(evt);
            }
        });

        riwayat.setFont(new java.awt.Font("Google Sans", 1, 18)); // NOI18N
        riwayat.setForeground(new java.awt.Color(255, 255, 255));
        riwayat.setText("Riwayat");
        riwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beranda)
                .addGap(48, 48, 48)
                .addComponent(gadai)
                .addGap(45, 45, 45)
                .addComponent(riwayat)
                .addGap(42, 42, 42)
                .addComponent(profil)
                .addGap(42, 42, 42)
                .addComponent(logout)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(beranda)
                        .addComponent(logout)
                        .addComponent(profil)
                        .addComponent(gadai)
                        .addComponent(riwayat)))
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(13, 13, 13))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        tabelRiwayat.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        tabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelRiwayat.setGridColor(new java.awt.Color(245, 245, 245));
        tabelRiwayat.setRowMargin(0);
        tabelRiwayat.setSelectionBackground(new java.awt.Color(0, 77, 67));
        tabelRiwayat.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRiwayatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelRiwayat);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjavadimas/img/logo1-removebg-preview.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Google Sans", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 171, 78));
        jLabel13.setText("GADAI EMAS");

        jLabel14.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(191, 215, 48));
        jLabel14.setText("cara cepat gadai emas");

        jLabel24.setFont(new java.awt.Font("Google Sans", 1, 26)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 77, 67));
        jLabel24.setText("Riwayat");

        jLabel25.setFont(new java.awt.Font("Google Sans", 1, 26)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 171, 78));
        jLabel25.setText("Transaksi");

        jLabel41.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel41.setText("Semua transaksi yang anda lakukan akan masuk ke dalam tabel ini, anda hanya perlu ");

        jLabel42.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel42.setText("mengklik salah satu data dibawah ini untuk mengecek transaksinya");

        jLabel5.setFont(new java.awt.Font("Google Sans", 0, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Klik tabel diatas untuk melihat data !!!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(182, 182, 182))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25))
                            .addComponent(jLabel41))
                        .addGap(36, 36, 36))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel13)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel41)
                .addGap(0, 0, 0)
                .addComponent(jLabel42)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));

        jLabel34.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel34.setText("Jenis Emas");

        jLabel35.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel35.setText("Jumlah Keping");

        jLabel36.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel36.setText("Berat Keping");

        jLabel37.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel37.setText("Kelengkapan Surat");

        jLabel38.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel38.setText("Kantor Pelayanan");

        jLabel39.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel39.setText("Jadwal Kedatangan");

        jLabel40.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel40.setText("Waktu Kedatangan");

        waktu_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        waktu_fiks.setText("-");

        jadwal_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jadwal_fiks.setText("-");

        kantor_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        kantor_fiks.setText("-");

        surat_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        surat_fiks.setText("-");

        berat_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        berat_fiks.setText("-");

        jumlah_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jumlah_fiks.setText("-");

        jenis_fiks.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jenis_fiks.setText("-");

        jLabel26.setFont(new java.awt.Font("Google Sans", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 77, 67));
        jLabel26.setText("Jumlah");

        jLabel27.setFont(new java.awt.Font("Google Sans", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 171, 78));
        jLabel27.setText("Pinjaman");

        TotalAkhir.setFont(new java.awt.Font("Google Sans", 1, 20)); // NOI18N
        TotalAkhir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalAkhir.setText("Rp.  -");
        TotalAkhir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        reset.setBackground(new java.awt.Color(0, 171, 78));
        reset.setFont(new java.awt.Font("Google Sans", 1, 20)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Bayar");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(14, 115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel40))
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel34))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(waktu_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(berat_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jenis_fiks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(surat_fiks)
                                    .addComponent(jadwal_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kantor_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(TotalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(0, 0, 0)
                .addComponent(TotalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jenis_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jumlah_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(berat_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(surat_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(kantor_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jadwal_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(waktu_fiks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        MenuUtama main = new MenuUtama(user);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_berandaMouseClicked

    private void berandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseEntered
        beranda.setForeground(new Color(186, 211, 51));
        beranda.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_berandaMouseEntered

    private void berandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseExited
        beranda.setForeground(new Color(255, 255, 255));
        beranda.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_berandaMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(new Color(186, 211, 51));
        logout.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(new Color(255, 255, 255));
        logout.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_logoutMouseExited

    private void profilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseClicked
        
        try {
            Profil prof = new Profil(user);
            prof.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Riwayat.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_profilMouseClicked

    private void profilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseEntered
        profil.setForeground(new Color(186, 211, 51));
        profil.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_profilMouseEntered

    private void profilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseExited
        profil.setForeground(new Color(255, 255, 255));
        profil.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_profilMouseExited

    private void gadaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gadaiMouseClicked
        Gadai gad = new Gadai(user);
        gad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gadaiMouseClicked

    private void gadaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gadaiMouseEntered
        gadai.setForeground(new Color(186, 211, 51));
        gadai.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_gadaiMouseEntered

    private void gadaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gadaiMouseExited
        gadai.setForeground(new Color(255, 255, 255));
        gadai.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_gadaiMouseExited

    private void riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseClicked
        
        try {
            Riwayat riw = new Riwayat(user);
            riw.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada : " +ex);
        }
        this.dispose();
    }//GEN-LAST:event_riwayatMouseClicked

    private void riwayatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseEntered
        riwayat.setForeground(new Color(186, 211, 51));
        riwayat.setFont(new Font("Google Sans", Font.BOLD, 19));
    }//GEN-LAST:event_riwayatMouseEntered

    private void riwayatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseExited
        riwayat.setForeground(new Color(255, 255, 255));
        riwayat.setFont(new Font("Google Sans", Font.BOLD, 18));
    }//GEN-LAST:event_riwayatMouseExited

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        try {
            Bayar bay = new Bayar(total, user);
            bay.setVisible(true);
            TotalAkhir.setText("Rp. -");
            jenis_fiks.setText("-");
            jumlah_fiks.setText("-");
            berat_fiks.setText("-");
            surat_fiks.setText("-");
            kantor_fiks.setText("-");
            jadwal_fiks.setText("-");
            waktu_fiks.setText("-");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada : " + e);
            
        }
    }//GEN-LAST:event_resetActionPerformed

    private void tabelRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRiwayatMouseClicked
        int baris = tabelRiwayat.getSelectedRow();
        jenis_fiks.setText(tabelRiwayat.getModel().getValueAt(baris, 1).toString());
        jumlah_fiks.setText(tabelRiwayat.getModel().getValueAt(baris, 2).toString());
        berat_fiks.setText(tabelRiwayat.getModel().getValueAt(baris, 3).toString());
        surat_fiks.setText(tabelRiwayat.getModel().getValueAt(baris, 4).toString());
        kantor_fiks.setText(tabelRiwayat.getModel().getValueAt(baris, 5).toString());
        jadwal_fiks.setText(tabelRiwayat.getModel().getValueAt(baris, 6).toString());
        waktu_fiks.setText(tabelRiwayat.getModel().getValueAt(baris, 7).toString());
        TotalAkhir.setText("Rp.  " + tabelRiwayat.getModel().getValueAt(baris, 8).toString());
        total = tabelRiwayat.getModel().getValueAt(baris, 8).toString();
    }//GEN-LAST:event_tabelRiwayatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalAkhir;
    private javax.swing.JLabel beranda;
    private javax.swing.JLabel berat_fiks;
    private javax.swing.JLabel gadai;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jadwal_fiks;
    private javax.swing.JLabel jenis_fiks;
    private javax.swing.JLabel jumlah_fiks;
    private javax.swing.JLabel kantor_fiks;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel profil;
    private javax.swing.JButton reset;
    private javax.swing.JLabel riwayat;
    private javax.swing.JLabel surat_fiks;
    private javax.swing.JTable tabelRiwayat;
    private javax.swing.JLabel waktu_fiks;
    // End of variables declaration//GEN-END:variables
}
